#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/resource.h>

#include <bpf/libbpf.h>

// generated skeleton header (generated via bpftool)
#include "program.skel.h"

#include "common.h"

// global flag for shutdown (volatile bc signal handler modifies it)
static volatile sig_atomic_t exiting = 0;

static void sig_handler(int sig) {
    (void)sig; // unused but required by handler
    exiting = 1;
}

static int handle_event(void *ctx, void *data, size_t data_size) 
{
    (void)ctx; // required by func again 
    const struct event *e = data;
    
    // sizes must match 
    if (data_size < sizeof(*e)) {
        fprintf(stderr, "Error: event size mismatch\n");
        return 0;
    }

    printf("%-8d %-8d %-16s %s\n",
        e->pid,
        e->uid,
        e->comm,
        e->filename
    );

    return 0; // non zero return value would stop ring buffer consumer
}

// custom libbpf print callback for logging
static int libbpf_print_fn(enum libbpf_print_level level,
                            const char *format,
                            va_list args)
{
    // only print warnings + errors
    if (level == LIBBPF_DEBUG)
        return 0;
    
    // print to stderr with the format string and arguments 
    return vfprintf(stderr, format, args);
}

int main(int argc, char **argv) 
{
    (void)argc;
    (void)argv;

    // pointer to our BPF skeleton structure (generated by BPFtool)
    struct program_bpf *skel = NULL;

    // ring buffer pointer for consumption
    struct ring_buffer *rb = NULL;

    int err;

    // set up the custom libbpf logging
    libbpf_set_print(libbpf_print_fn);


    // open BPF skeleton, then parse ELF data
    skel = program_bpf__open();
    if(!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }


    // load + verify BPF programs
    // loads the bytecode into the kernel then runs verifier
    err = program_bpf__load(skel);
    if (err) {
        fprintf(stderr, "Failed to load BPF skeleton %d\n", err);
        goto cleanup;
    }

    // attaches BPF program to hooks
    // so it attaches it to sys_enter_execve
    // the skeleton knows where to attach based on SEC() 
    err = program_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach %d\n", err);
        goto cleanup;
    }

    // set up signal handlers for easy shutdown
    signal(SIGINT, sig_handler); // ctrl+C
    signal(SIGTERM, sig_handler); // kill cmd

    // create ring buffer consumer 
    rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
                                handle_event,
                                NULL,
                                NULL);
    
    if (!rb) {
        err = -1;
        fprintf(stderr, "Failed to create ring buffer\n");
        goto cleanup;
    }

    printf("%-8s %-8s %-16s %s\n", "PID", "UID", "COMM", "FILENAME");
    while (!exiting) {
        // ring_buffer__poll returns # of events consumed, or negative if error
        err = ring_buffer__poll(rb, 100);
        if (err == -EINTR) {
            err = 0;
            break;
        }

        if (err < 0) {
            fprintf(stderr, "Error polling ring buffer: %d\n", err);
            break;
        }
    }

cleanup:
    // same as normal destructors! (clean up in reverse order of init)
    ring_buffer__free(rb); 
    program_bpf__destroy(skel); // detaches programs + closes maps

    return err < 0 ? 1 : 0;
}