#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <sys/resource.h>

#include <bpf/libbpf.h>

// generated skeleton header (generated via bpftool)
#include "program.skel.h"

#include "common.h"

// global flag for shutdown (volatile bc signal handler modifies it)
static volatile sig_atomic_t exiting = 0;

static void sig_handler(int sig) {
    (void)sig; // unused but required by handler
    exiting = 1;
}

static int handle_event(void *ctx, void *data, size_t data_size) 
{
    (void)ctx; // required by func again 
    const struct event *e = data;
    
    // sizes must match 
    if (data_size < sizeof(*e)) {
        fprintf(stderr, "Error: event size mismatch\n");
        return 0;
    }

    printf("%-8d %-8d %-16s %s\n",
        e->pid,
        e->uid,
        e->comm,
        e->filename
    );

    return 0; // non zero return value would stop ring buffer consumer
}

// custom libbpf print callback for logging
static int libbpf_print_fn(enum libbpf_print_level level,
                            const char *format,
                            va_list args)
{
    // only print warnings + errors
    if (level == LIBBPF_DEBUG)
        return 0;
    
    // print to stderr with the format string and arguments 
    return vfprintf(stderr, format, args);
}

int main(int argc, char **argv) 
{
    (void)argc;
    (void)argv;

    // pointer to our BPF skeleton structure (generated by BPFtool)
    struct program_bpf *skel = NULL;

    // ring buffer pointer for consumption
    struct ring_buffer *rb = NULL;

    int err;

    // set up the custom libbpf logging
    libbpf_set_print(libbpf_print_fn);

    skel = program_bpf__open();
    if(!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }
}